/**
 * The D3D11 back end's one shader pair, as HLSL source (nv2a_draw_d3d11.c
 * compiles it at start-up).
 *
 * The vertex shader takes what the software path's vertex stage produced --
 * screen-space x, y, z with the clip-space w kept, as nv2a_vsh_run leaves
 * them -- and maps pixels back to clip space, times w so the GPU divides it
 * out again and interpolates texture coordinates with perspective. Colours
 * and fog interpolate across the screen without it, as xf_rows does.
 *
 * The pixel shader has three paths, chosen per batch (mode.x):
 *   0  flat: the texel alone, or the triangle's first vertex colour
 *      (raster_triangle: fixed-function batches, no combiners);
 *   1  texel times the interpolated colour (xf_rows without combiners);
 *   2  the register combiners, evaluated from their registers in the
 *      constant buffer: a line-for-line port of nv2a_rc_eval
 *      (nv2a_combiner.c) and of rc_stage_fetch (nv2a_draw_sw.c). Keep the
 *      three in step; the software ones are the reference.
 * Alpha test (mode.z, the GL function; 0 off) follows alpha_test_pass.
 *
 * ponytail: level 0 only (SampleLevel 0), as the software sampler; cube
 * maps and the bump/dot-product stage modes read as the software path's
 * fallbacks do, near enough: an unbound stage reads white.
 */
#ifndef NV2A_DRAW_D3D11_HLSL_H
#define NV2A_DRAW_D3D11_HLSL_H

static const char s_hlsl[] =
"Texture2D t0 : register(t0); Texture2D t1 : register(t1);\n"
"Texture2D t2 : register(t2); Texture2D t3 : register(t3);\n"
"SamplerState s0 : register(s0); SamplerState s1 : register(s1);\n"
"SamplerState s2 : register(s2); SamplerState s3 : register(s3);\n"
"cbuffer C : register(b0) {\n"
"  float4 rt;          /* x*rt.x+rt.z, y*rt.y+rt.w: pixels to NDC */\n"
"  float4 tscale[4];   /* per stage: coordinates to normalised */\n"
"  uint4  mode;        /* path, bound-stage bits, alpha func, alpha ref */\n"
"  uint4  stage;       /* stage program, clip-plane mode, control, fog */\n"
"  uint4  icw[8];      /* colour ICW, alpha ICW, colour OCW, alpha OCW */\n"
"  float4 cf0[8];      /* FACTOR0 per stage */\n"
"  float4 cf1[8];      /* FACTOR1 per stage */\n"
"  uint4  fin;         /* final combiner words 0, 1 */\n"
"  float4 fc0, fc1;    /* final combiner constants */\n"
"  float4 fogc;        /* fog colour, r g b */\n"
"  float4 fogp;        /* fog parameters 0, 1 */\n"
"};\n"
"struct VI {\n"
"  float4 p : POSITION; float4 d0 : COLOR0; float4 d1 : COLOR1;\n"
"  float4 fog : TEXCOORD4;\n"
"  float4 t0 : TEXCOORD0; float4 t1 : TEXCOORD1;\n"
"  float4 t2 : TEXCOORD2; float4 t3 : TEXCOORD3;\n"
"};\n"
"struct V {\n"
"  float4 p : SV_Position;\n"
"  nointerpolation float4 cf : COLOR0;\n"
"  noperspective float4 d0 : COLOR1;\n"
"  noperspective float4 d1 : COLOR2;\n"
"  noperspective float fog : FOG;\n"
"  float4 t0 : TEXCOORD0; float4 t1 : TEXCOORD1;\n"
"  float4 t2 : TEXCOORD2; float4 t3 : TEXCOORD3;\n"
"};\n"
"\n"
"/* fog_factor (nv2a_draw_sw.c): the fog unit, per vertex. */\n"
"float fog_factor(float d) {\n"
"  uint m = stage.w & 0xFFFF; float f;\n"
"  if (!(stage.w & 0x10000)) return 1.0;\n"
"  if (m == 0x800 || m == 0x802) f = fogp.x + exp2(d * fogp.y * 16.0) - 1.5;\n"
"  else if (m == 0x801 || m == 0x803)\n"
"    f = fogp.x + exp2(-d * d * fogp.y * fogp.y * 32.0) - 1.5;\n"
"  else f = fogp.x + d * fogp.y - 1.0;\n"
"  if (m == 0x802 || m == 0x803 || m == 0x804) f = abs(f);\n"
"  if (!(f == f)) f = 1.0;\n"
"  return saturate(f);\n"
"}\n"
"\n"
"V vs(VI i) {\n"
"  V o; float w = i.p.w;\n"
"  o.p = float4((i.p.x * rt.x + rt.z) * w, (i.p.y * rt.y + rt.w) * w,\n"
"               0.5 * w, w);\n"
"  o.cf = i.d0; o.d0 = i.d0; o.d1 = i.d1; o.fog = fog_factor(i.fog.x);\n"
"  o.t0 = i.t0; o.t1 = i.t1; o.t2 = i.t2; o.t3 = i.t3;\n"
"  return o;\n"
"}\n"
"\n"
"/* One stage's texel at coordinates c; an unbound stage reads white. */\n"
"float4 texel(Texture2D t, SamplerState s, uint st, float2 c) {\n"
"  if (!((mode.y >> st) & 1)) return float4(1, 1, 1, 1);\n"
"  return t.SampleLevel(s, c * tscale[st].xy, 0);\n"
"}\n"
"\n"
"/* rc_stage_fetch: what stage st contributes, by its program mode. */\n"
"float4 stage_fetch(Texture2D t, SamplerState s, uint st, float4 c) {\n"
"  uint m = (stage.x >> (st * 5)) & 31, j;\n"
"  if (m == 0) return float4(0, 0, 0, 1);\n"
"  if (m == 1 || m == 2) {\n"
"    float q = c.w != 0.0 ? c.w : 1.0;\n"
"    return texel(t, s, st, c.xy / q);\n"
"  }\n"
"  if (m == 3) return texel(t, s, st, c.xy);\n"
"  if (m == 4) return saturate(c);\n"
"  if (m == 5) {\n"
"    [unroll] for (j = 0; j < 4; j++) {\n"
"      bool ge = (stage.y >> (st * 4 + j)) & 1;\n"
"      if (ge ? c[j] >= 0.0 : c[j] < 0.0) discard;\n"
"    }\n"
"  }\n"
"  return float4(0, 0, 0, 0);\n"
"}\n"
"\n"
"/* map_in / map_out (nv2a_combiner.c). */\n"
"float map_in(float x, uint b) {\n"
"  float p = max(x, 0.0);\n"
"  switch ((b >> 5) & 7) {\n"
"  case 0: return p;\n"
"  case 1: return 1.0 - saturate(x);\n"
"  case 2: return 2.0 * p - 1.0;\n"
"  case 3: return -2.0 * p + 1.0;\n"
"  case 4: return p - 0.5;\n"
"  case 5: return -p + 0.5;\n"
"  case 6: return x;\n"
"  default: return -x;\n"
"  }\n"
"}\n"
"float map_out(float x, uint m) {\n"
"  if (m == 0x08) return x - 0.5;\n"
"  if (m == 0x10) return x * 2.0;\n"
"  if (m == 0x18) return (x - 0.5) * 2.0;\n"
"  if (m == 0x20) return x * 4.0;\n"
"  if (m == 0x30) return x * 0.5;\n"
"  return x;\n"
"}\n"
"float3 map_out3(float3 x, uint m) {\n"
"  return float3(map_out(x.r, m), map_out(x.g, m), map_out(x.b, m));\n"
"}\n"
"float3 rd_rgb(float4 R[16], uint b) {\n"
"  float4 r = R[b & 15];\n"
"  float3 x = (b & 0x10) ? r.aaa : r.rgb;\n"
"  return float3(map_in(x.r, b), map_in(x.g, b), map_in(x.b, b));\n"
"}\n"
"float rd_a(float4 R[16], uint b) {\n"
"  float4 r = R[b & 15];\n"
"  return map_in((b & 0x10) ? r.a : r.b, b);\n"
"}\n"
"\n"
"/* nv2a_rc_eval. Registers: 0 zero, 1 c0, 2 c1, 3 fog, 4 v0, 5 v1,\n"
" * 8-11 t0-t3, 12 r0, 13 r1, 14 v1+r0, 15 E*F. */\n"
"float4 combine(float4 v0, float4 v1, float fogf, float4 T[4]) {\n"
"  float4 R[16]; uint k, s, n = min(stage.z & 0xFF, 8), fl8 = stage.z >> 8;\n"
"  [unroll] for (k = 0; k < 16; k++) R[k] = float4(0, 0, 0, 0);\n"
"  R[3] = float4(fogc.rgb, fogf); R[4] = v0; R[5] = v1;\n"
"  R[8] = T[0]; R[9] = T[1]; R[10] = T[2]; R[11] = T[3];\n"
"  R[12].a = (stage.x & 31) ? T[0].a : 1.0;\n"
"  [loop] for (s = 0; s < n; s++) {\n"
"    uint ic = icw[s].x, ai = icw[s].y, oc = icw[s].z, ao = icw[s].w;\n"
"    uint fl = oc >> 12, afl = ao >> 12, d;\n"
"    float3 A, B, Cc, D, pab, pcd, sum, ab, cd, ms;\n"
"    float aA, aB, aC, aD, apab, apcd, asum, aab, acd, ams;\n"
"    bool mux;\n"
"    R[1] = cf0[(fl8 & 0x010) ? s : 0]; R[2] = cf1[(fl8 & 0x100) ? s : 0];\n"
"    mux = (fl8 & 1) ? R[12].a >= 0.5 : ((int)(R[12].a * 255.0) & 1) != 0;\n"
"    A = rd_rgb(R, ic >> 24); B = rd_rgb(R, ic >> 16);\n"
"    Cc = rd_rgb(R, ic >> 8); D = rd_rgb(R, ic);\n"
"    aA = rd_a(R, ai >> 24); aB = rd_a(R, ai >> 16);\n"
"    aC = rd_a(R, ai >> 8);  aD = rd_a(R, ai);\n"
"    pab = (fl & 2) ? dot(A, B).xxx : A * B;\n"
"    pcd = (fl & 1) ? dot(Cc, D).xxx : Cc * D;\n"
"    sum = (fl & 4) ? (mux ? pcd : pab) : pab + pcd;\n"
"    ab = clamp(map_out3(pab, fl & 0x38), -1.0, 1.0);\n"
"    cd = clamp(map_out3(pcd, fl & 0x38), -1.0, 1.0);\n"
"    ms = clamp(map_out3(sum, fl & 0x38), -1.0, 1.0);\n"
"    apab = aA * aB; apcd = aC * aD;\n"
"    asum = (afl & 4) ? (mux ? apcd : apab) : apab + apcd;\n"
"    aab = clamp(map_out(apab, afl & 0x38), -1.0, 1.0);\n"
"    acd = clamp(map_out(apcd, afl & 0x38), -1.0, 1.0);\n"
"    ams = clamp(map_out(asum, afl & 0x38), -1.0, 1.0);\n"
"    d = (oc >> 4) & 15;\n"
"    if (d) { R[d].rgb = ab; if (fl & 0x80) R[d].a = ab.b; }\n"
"    d = oc & 15;\n"
"    if (d) { R[d].rgb = cd; if (fl & 0x40) R[d].a = cd.b; }\n"
"    d = (oc >> 8) & 15;\n"
"    if (d) R[d].rgb = ms;\n"
"    d = (ao >> 4) & 15; if (d) R[d].a = aab;\n"
"    d = ao & 15;        if (d) R[d].a = acd;\n"
"    d = (ao >> 8) & 15; if (d) R[d].a = ams;\n"
"    R[0] = float4(0, 0, 0, 0);\n"
"  }\n"
"  if (fin.x || fin.y) {\n"
"    uint w0 = fin.x, w1 = fin.y, ff = w1 & 0xFF;\n"
"    float3 a, b, A, B, Cc, D, E, F;\n"
"    float4 o;\n"
"    R[1] = fc0; R[2] = fc1;\n"
"    a = (ff & 0x40) ? 1.0 - R[5].rgb : R[5].rgb;\n"
"    b = (ff & 0x20) ? 1.0 - R[12].rgb : R[12].rgb;\n"
"    R[14] = float4((ff & 0x80) ? saturate(a + b) : a + b, 0.0);\n"
"    E = rd_rgb(R, w1 >> 24); F = rd_rgb(R, w1 >> 16);\n"
"    R[15] = float4(E * F, 0.0);\n"
"    A = rd_rgb(R, w0 >> 24); B = rd_rgb(R, w0 >> 16);\n"
"    Cc = rd_rgb(R, w0 >> 8); D = rd_rgb(R, w0);\n"
"    o.rgb = D + Cc * (1.0 - A) + B * A;\n"
"    o.a = rd_a(R, w1 >> 8);\n"
"    return saturate(o);\n"
"  }\n"
"  return saturate(R[12]);\n"
"}\n"
"\n"
"float4 ps(V i) : SV_Target {\n"
"  float4 o;\n"
"  if (mode.x == 2) {\n"
"    float4 T[4];\n"
"    T[0] = stage_fetch(t0, s0, 0, i.t0);\n"
"    T[1] = stage_fetch(t1, s1, 1, i.t1);\n"
"    T[2] = stage_fetch(t2, s2, 2, i.t2);\n"
"    T[3] = stage_fetch(t3, s3, 3, i.t3);\n"
"    o = combine(i.d0, i.d1, i.fog, T);\n"
"  } else {\n"
"    float4 t = texel(t0, s0, 0, i.t0.xy);\n"
"    if (mode.x == 1) o = t * i.d0;\n"
"    else o = (mode.y & 1) ? t : i.cf;\n"
"  }\n"
"  if (mode.z) {\n"
"    int v = (int)(o.a * 255.0 + 0.5), r = (int)mode.w;\n"
"    bool ok = true;\n"
"    switch (mode.z) {\n"
"    case 0x200: ok = false; break;\n"
"    case 0x201: ok = v <  r; break;\n"
"    case 0x202: ok = v == r; break;\n"
"    case 0x203: ok = v <= r; break;\n"
"    case 0x204: ok = v >  r; break;\n"
"    case 0x205: ok = v != r; break;\n"
"    case 0x206: ok = v >= r; break;\n"
"    }\n"
"    if (!ok) discard;\n"
"  }\n"
"  return o;\n"
"}\n";

#endif
