cmake_minimum_required(VERSION 3.20)
project(kernel_query_attributes_test C)
set(CMAKE_C_STANDARD 11)
add_subdirectory(../.. runtime)
add_executable(kernel_query_attributes_test test_main.c)
target_include_directories(kernel_query_attributes_test PRIVATE ../../src/kernel)
target_link_libraries(kernel_query_attributes_test PRIVATE xboxrecomp)
enable_testing()
add_test(NAME kernel_query_attributes_test COMMAND kernel_query_attributes_test)
